### ISSUE TITLE
no support for arrays

### ISSUE THREAD

**Issue by mmkathurima** [reportmill/SnapCode#8]
The following code raises `Error: Can't resolve id: length`
```java
int[] arr = IntStream.range(0,10).boxed()
        .mapToInt(Integer::intValue)
        .toArray();
for (int i = 0; i < arr.length; i++)
    System.out.println(arr[i]);
```
That is the `length` variable of `int[]`
Arrays are treated as `java.lang.Object`.

**Comment by reportmill** [comment]
I think this one didn't work because of the MethodRef, which is causing a couple problems. I'll work on that problem next (in the "no method ref support' issue).

However, while working on this one, I fixed the error reporting so now it reports an error "Invalid assignment type", which made testing much easier. So we did get some improvement here.

I released the fixes in an update - notice the jar name has changed since it's the first of the month (now v2023.08): 

    https://reportmill.com/SnapCode/cj/SnapCodeAll-2023.08.jar
